let token=localStorage.getItem('dgca_token'),user=null,mode='login',cfg={},subject=null,questions=[],answers={},practiceMode=true,lectureCatalog=[],paidVideoActive=false,protectionTimer=null,mockTimer=null,mockDeadline=0,mockSubmitted=false;
const $=x=>document.getElementById(x);const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const PURCHASE_KEY='dgca_access_'+(localStorage.getItem('dgca_token')||'guest');
function getPurchases(){try{return JSON.parse(localStorage.getItem('dgca_purchases_'+(user?.id||'guest'))||'{}')}catch{return {}}}
function setPurchases(data){localStorage.setItem('dgca_purchases_'+(user?.id||'guest'),JSON.stringify(data))}
function hasPurchased(type){return !!getPurchases()[type]}
function purchaseItem(type,label,amount){if(!user){auth('login');return;}if(hasPurchased(type)){return true;}if(confirm(`${label} costs ₹${Number(amount).toLocaleString('en-IN')}. Do you want to unlock it?`)){let p=getPurchases();p[type]=true;setPurchases(p);return true;}return false;}
async function api(u,o={}){o.headers={...(o.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};let r=await fetch(u,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Request failed');return d}
async function init(){try{cfg=await api('/api/config')}catch{}if(token)try{user=(await api('/api/auth/me')).user;nav();loadSubjects()}catch{logout(false)}else renderDemoSubjects()}init();
function nav(){$('loginBtn').classList.toggle('hide',!!user);$('signupBtn').classList.toggle('hide',!!user);$('logoutBtn').classList.toggle('hide',!user);$('performanceLink').classList.toggle('hide',!user);if(user?.role==='admin')$('admin').classList.remove('hide')}
function auth(m){mode=m;$('authModal').classList.remove('hide');$('authTitle').textContent=m==='register'?'Create account':'Login';$('name').classList.toggle('hide',m!=='register');$('authSubmit').textContent=m==='register'?'Create Account':'Login';$('toggleAuth').textContent=m==='register'?'Already have an account? Login':'Create an account'}function toggleAuth(){auth(mode==='login'?'register':'login')}function closeModal(id){$(id).classList.add('hide');if(id==='videoModal'||id==='pdfModal')setPaidVideoProtection(false)}
$('authForm').onsubmit=async e=>{e.preventDefault();try{let body={email:$('email').value,password:$('password').value};if(mode==='register')body.name=$('name').value;let d=await api(mode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(body)});token=d.token;user=d.user;localStorage.setItem('dgca_token',token);closeModal('authModal');nav();loadSubjects()}catch(e){$('authErr').textContent=e.message}};
function logout(go=true){token=null;user=null;localStorage.removeItem('dgca_token');nav();renderDemoSubjects();if(go)location.hash='home'}function goSubjects(){if(user)location.hash='subjects';else auth('login')}
function renderDemoSubjects(){let a=[['⚖️','Air Regulations','paid'],['🌤️','Meteorology','paid'],['🧭','Air Navigation','paid'],['⚙️','Technical General','paid'],['📡','RTR','paid'],['✈️','Piper Archer III','paid']];$('grid').innerHTML=a.map(x=>card({shortName:x[0],name:x[1],access:x[2],description:'Paid question bank',unlocked:false})).join('')}
function card(s){let unlocked=s.unlocked,b=s.access==='free';return `<div class="card"><div><span class="code">${esc(s.shortName)}</span><span class="badge ${b?'free':''}">${b?'Free':'Paid'} ${!b&&!unlocked?'🔒':''}</span></div><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><button class="${unlocked?'':'outline'}" onclick="${unlocked?`openSubject('${s.id}')`:`${user?'unlockQuestionBank()':'auth(\'login\')'}`} ">${unlocked?'Start Practice':user?'Unlock for ₹99':'Login to Start'}</button></div>`}
async function loadSubjects(){try{let a=await api('/api/subjects');$('grid').innerHTML=a.map(card).join('');if(user.role==='admin')loadAdmin()}catch(e){$('grid').innerHTML='<p>'+esc(e.message)+'</p>'}}
async function loadLectureCatalog(){try{let files=['air-regulations','meteorology','air-navigation'];lectureCatalog=await Promise.all(files.map(file=>fetch(`/lectures/${file}.json`).then(response=>{if(!response.ok)throw Error('Lecture file unavailable');return response.json()})));renderLectureSubjects()}catch(e){$('lectureSubjects').innerHTML='<p>Lectures could not be loaded.</p>'}}
function renderLectureSubjects(){$('lectureSubjects').classList.remove('hide');$('lectureDetail').classList.add('hide');$('lectureSubjects').innerHTML=lectureCatalog.map(item=>{let purchased=hasPurchased(`videoCourse:${item.id}`),progress=getLectureProgress(item.id,item.lectures);return `<article class="lecture-course-card"><div class="lecture-subject-heading"><span class="code">${esc(item.shortName)}</span><div><h3>${esc(item.name)}</h3><p>${item.lectures.length} lectures · First lecture free</p></div><span class="course-status ${purchased?'unlocked':''}">${purchased?'Unlocked':'Locked Course'}</span></div><div class="progress-track"><span style="width:${progress}%"></span></div><div class="course-meta"><span>${progress}% complete</span><button onclick="showLectureSubject('${esc(item.id)}')">View Chapters & Lectures</button></div></article>`}).join('')}
function getLectureProgress(subjectId,lectures){let watched=JSON.parse(localStorage.getItem(`dgca_lecture_progress_${subjectId}_${user?.id||'guest'}`)||'{}');return lectures.length?Math.round(Object.keys(watched).length/lectures.length*100):0}
function updateLectureProgress(subjectId,lectures){let progress=getLectureProgress(subjectId,lectures);if($('progressLabel'))$('progressLabel').textContent=`${progress}% complete`;if($('progressBar'))$('progressBar').style.width=`${progress}%`}
function showLectureSubject(subjectId){let item=lectureCatalog.find(subjectItem=>subjectItem.id===subjectId);if(!item)return;let purchased=hasPurchased(`videoCourse:${item.id}`),price=Number(item.price),groups={};item.lectures.forEach((lecture,index)=>{let chapter=lecture.chapter||`Chapter ${Math.floor(index/3)+1}`;(groups[chapter]??=[]).push({lecture,index})});$('lectureSubjects').classList.add('hide');$('lectureDetail').classList.remove('hide');$('lectureDetail').innerHTML=`<div class="lecture-detail-head"><button class="outline" onclick="renderLectureSubjects()">← All Subjects</button><div class="lecture-detail-title"><span class="code">${esc(item.shortName)}</span><div><small>VIDEO COURSE</small><h2>${esc(item.name)}</h2><p>${item.lectures.length} lectures · First introduction free</p></div></div><div class="detail-actions"><button onclick="startSubjectPractice('${esc(item.id)}')">Start Practicing</button>${purchased?'<span class="course-status unlocked">Course Unlocked</span>':`<button class="outline" onclick="purchaseLectureCourse('${esc(item.id)}')">Purchase Course · ₹${price.toLocaleString('en-IN')}</button>`}</div></div><div class="lecture-progress-card"><div><strong>Course progress</strong><span id="progressLabel">${getLectureProgress(item.id,item.lectures)}% complete</span></div><div class="progress-track"><span id="progressBar" style="width:${getLectureProgress(item.id,item.lectures)}%"></span></div></div><div class="lecture-chapters">${Object.entries(groups).map(([chapter,entries])=>`<section class="lecture-chapter"><div class="chapter-heading"><h3>${esc(chapter)}</h3><span>${entries.length} lectures</span></div>${entries.map(({lecture,index})=>{let free=lecture.free===true||index===0;return `<div class="lecture-row"><div><span class="lecture-number">${String(index+1).padStart(2,'0')}</span><div><strong>${esc(lecture.title)}</strong><small>${free?'Free introduction':purchased?'Available now':'Purchase course to unlock'}</small></div></div><button class="${free||purchased?'':'outline'}" onclick="openCatalogLecture('${esc(item.id)}','${esc(lecture.id)}')">${free?'Watch Lecture':purchased?'Watch Lecture':'🔒 Locked'}</button></div>`}).join('')}</section>`).join('')}</div>`}
const baseShowLectureSubject=showLectureSubject;showLectureSubject=function(subjectId){baseShowLectureSubject(subjectId);addLecturePdfResources(subjectId)};
function addLecturePdfResources(subjectId){let item=lectureCatalog.find(subjectItem=>subjectItem.id===subjectId);if(!item)return;let chapterRows={};document.querySelectorAll('.lecture-chapter').forEach(chapter=>{chapterRows[chapter.querySelector('h3')?.textContent]=[...chapter.querySelectorAll('.lecture-row')]});item.lectures.forEach((lecture,index)=>{if(!lecture.pdfUrl)return;let chapter=lecture.chapter||`Chapter ${Math.floor(index/3)+1}`,row=chapterRows[chapter]?.shift();if(row)row.insertAdjacentHTML('afterend',`<div class="lecture-resource"><span>PDF notes available</span><button class="outline" onclick="openLecturePdf('${esc(item.id)}','${esc(lecture.id)}')">Open PDF</button></div>`)});}
function openLecturePdf(subjectId,lectureId){let item=lectureCatalog.find(subjectItem=>subjectItem.id===subjectId),lecture=item?.lectures.find(lectureItem=>lectureItem.id===lectureId);if(!item||!lecture?.pdfUrl)return;let free=lecture.free===true||item.lectures.indexOf(lecture)===0;if(!free&&!user){auth('login');return;}if(!free&&!hasPurchased(`videoCourse:${subjectId}`)){if(!purchaseItem(`videoCourse:${subjectId}`,`${item.name} course`,item.price))return;showLectureSubject(subjectId)}$('pdfTitle').textContent=`${item.name} · ${lecture.title}`;$('pdfFrame').src=lecture.pdfUrl;setPaidVideoProtection(!free);$('pdfModal').classList.remove('hide');}
function purchaseLectureCourse(subjectId){let item=lectureCatalog.find(subjectItem=>subjectItem.id===subjectId);if(!item||!user){auth('login');return;}if(purchaseItem(`videoCourse:${subjectId}`,`${item.name} course`,item.price)){if(location.hash==='#video-lecture')showLectureSubject(subjectId);else alert(`${item.name} course purchased. All lectures are now unlocked.`)}}
function purchaseLectureBundle(){if(!user){auth('login');return;}if(purchaseItem('videoBundle','Complete Lecture Bundle',12999)){let purchases=getPurchases();['air-regulations','meteorology','air-navigation'].forEach(subjectId=>purchases[`videoCourse:${subjectId}`]=true);purchases.questionBank=true;setPurchases(purchases);renderLectureSubjects();alert('Complete bundle unlocked: all lectures and the question bank are now available.');}}
function startSubjectPractice(subjectId){if(!user){auth('login');return;}location.hash='subjects';setTimeout(()=>{let item=lectureCatalog.find(subjectItem=>subjectItem.id===subjectId),questionSubject=[...document.querySelectorAll('#grid .card h3')].find(title=>title.textContent===item?.name);questionSubject?.closest('.card').querySelector('button')?.click()},0)}
function unlockQuestionBank(){if(!user){auth('login');return;}if(purchaseItem('questionBank','Question Bank',99)){alert('Question Bank unlocked for ₹99.');loadSubjects();}}
async function pay(){if(!user)return auth('login');$('price').textContent='99';$('payNote').textContent='Question bank access: ₹99. Unlock study access to begin.';$('payModal').classList.remove('hide');}
async function startPayment(){try{let o=await api('/api/payment/create-order',{method:'POST'});if(o.demo){await api('/api/payment/demo-success',{method:'POST',body:'{}'});alert('Demo payment successful!');closeModal('payModal');if(purchaseItem('questionBank','Question Bank',99)){loadSubjects();}return}if(!window.Razorpay){await new Promise((ok,no)=>{let s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=ok;s.onerror=no;document.head.append(s)})}new Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:'DGCAPrep',description:'DGCA CPL Question Bank',order_id:o.orderId,handler:async r=>{await api('/api/payment/verify',{method:'POST',body:JSON.stringify(r)});alert('Payment verified!');loadSubjects()},theme:{color:'#1769ff'}}).open()}catch(e){alert(e.message)}}$('payBtn').onclick=startPayment;
function clearMockTimer(){if(mockTimer){clearInterval(mockTimer);mockTimer=null}mockDeadline=0}
const MOCK_DURATIONS={'air-regulations':120,'meteorology':120,'air-navigation':150,'technical-general':150,'rtr':90,'piper-archer-iii':90};
function formatTime(seconds){let minutes=Math.floor(seconds/60),remaining=seconds%60;return `${String(minutes).padStart(2,'0')}:${String(remaining).padStart(2,'0')}`}
function updateMockTimer(){let seconds=Math.max(0,Math.ceil((mockDeadline-Date.now())/1000));if($('mockTimer'))$('mockTimer').textContent=formatTime(seconds);if(seconds===0){clearMockTimer();submitTest(true)}}
function startMockTimer(){clearMockTimer();let minutes=MOCK_DURATIONS[subject.id];if(practiceMode||!minutes)return;mockDeadline=Date.now()+minutes*60*1000;updateMockTimer();mockTimer=setInterval(updateMockTimer,1000)}
async function openSubject(id){try{clearMockTimer();if(!user){auth('login');return;}if(!hasPurchased('questionBank')){if(!purchaseItem('questionBank','Question Bank',99)){return;} }let d=await api('/api/subjects/'+id+'?mode=practice');subject=d.subject;questions=d.questions;answers={};$('study').classList.remove('hide');$('subjects').classList.add('hide');renderStudy(d.books,d.chapters||[])}catch(e){if(e.message.includes('Paid'))pay();else alert(e.message)}}
function renderStudy(books,chapters){if(!books)books=[{id:subject.id,name:subject.name,chapters:chapters.map(name=>({name,count:questions.filter(q=>q.chapter===name).length}))}];if(books.some(book=>book.id!=='technical-general'&&book.chapters.every(chapter=>!chapter.count))){books=books.map(book=>{let bookQuestions=questions.filter(question=>question.bookId===book.id),names=[...new Set(bookQuestions.map(question=>String(question.chapter||'General').trim()))];return names.length?{...book,chapters:names.map(name=>({name,count:bookQuestions.filter(question=>String(question.chapter||'General').trim()===name).length}))}:book})}$('studyBox').innerHTML=`<div class="book-page"><button class="outline" onclick="$('study').classList.add('hide');$('subjects').classList.remove('hide');loadSubjects()">← Back to Subjects</button><div class="book-heading"><span class="book-icon">${esc(subject.shortName)}</span><div><small>TECHNICAL GENERAL / QUESTION BOOKS</small><h2>${esc(subject.name)}</h2><p>Choose a book, then practise a chapter or take its mock test.</p></div></div><button onclick="openCombinedMock()">Mock Test: All Books</button><div class="books-list">${books.map(book=>`<div class="book-card"><div class="book-card-title"><span class="book-icon">&#128218;</span><div><h3>${esc(book.name)}</h3><small>${book.chapters.length} chapters</small></div></div><div class="chapter-list">${book.chapters.map((chapter,index)=>`<div class="chapter-card"><div><span class="chapter-number">${String(index+1).padStart(2,'0')}</span><strong>${esc(chapter.name)}</strong><small>${chapter.count} questions</small></div><div><button onclick="openChapter('${esc(book.id)}','${esc(chapter.name)}',true)">Practice</button><button class="outline" onclick="openChapter('${esc(book.id)}','${esc(chapter.name)}',false)">Mock Test</button></div></div>`).join('')}</div></div>`).join('')}</div></div>`}
async function openChapter(bookId,chapter,testMode){try{clearMockTimer();practiceMode=testMode;let query='?mode='+(practiceMode?'practice':'mock')+'&chapter='+encodeURIComponent(chapter);if(bookId!==subject.id)query+='&book='+encodeURIComponent(bookId);let d=await api('/api/subjects/'+subject.id+query);questions=d.questions;answers={};renderQuestions(`${bookId} / ${chapter}`)}catch(e){alert(e.message)}}
async function openCombinedMock(){try{clearMockTimer();practiceMode=false;let d=await api('/api/subjects/'+subject.id+'?mode=mock');questions=d.questions;answers={};renderQuestions('All Books')}catch(e){alert(e.message)}}
function renderQuestions(title){mockSubmitted=false;$('studyBox').innerHTML=`<div class="card"><button class="outline" onclick="openSubject('${esc(subject.id)}')">← Back to Books</button><small>${esc(subject.name)} / ${esc(title)}</small><div class="test-heading"><h2>${practiceMode?'Practice':'Mock Test'}</h2>${practiceMode?'':`<strong class="mock-timer" id="mockTimer" aria-live="polite">--:--</strong>`}</div><div id="qlist"></div><button id="submitTestButton" onclick="submitTest()">${practiceMode?'Check Answers':'Submit Mock Test'}</button></div>`;renderQ('All');startMockTimer()}
function filterQ(el,c){document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderQ(c)}function renderQ(c){let arr=c==='All'?questions:questions.filter(q=>q.chapter===c);$('qlist').innerHTML=arr.map((q,i)=>{let selected=answers[q.id],answered=selected!==undefined;return `<div class="question"><small>QUESTION ${i+1}</small><h3>${esc(q.question)}</h3>${q.options.map((o,j)=>{let state=practiceMode&&answered?(j===q.answer?'correct-option':j===selected?'wrong-option':''):'';return `<button class="option ${selected===j?'sel ':''}${state}" onclick="answers['${esc(q.id)}']=${j};renderQ('${esc(c)}')"><span class="option-letter">${String.fromCharCode(65+j)}</span><span>${esc(o)}</span></button>`}).join('')}</div>`}).join('')}
function performanceKey(){return 'dgca_performance_'+user.id}
function savePerformance(result){let all=JSON.parse(localStorage.getItem(performanceKey())||'{}'),old=all[subject.id]||{};all[subject.id]={attempts:(old.attempts||0)+1,lastPercentage:result.percentage,bestPercentage:Math.max(old.bestPercentage||0,result.percentage)};localStorage.setItem(performanceKey(),JSON.stringify(all))}
async function submitTest(autoSubmitted=false){if(mockSubmitted)return;mockSubmitted=true;clearMockTimer();let button=$('submitTestButton');if(button)button.disabled=true;try{let d=await api('/api/subjects/'+subject.id+'/check',{method:'POST',body:JSON.stringify({answers})});savePerformance(d);$('qlist').insertAdjacentHTML('afterbegin',`<div class="result"><b>Score ${d.score}/${d.attempted}</b><br>Accuracy ${d.percentage}%${autoSubmitted?'<br>Time expired.':''}</div>`);document.querySelectorAll('.question').forEach((q,i)=>{let r=d.results[i];if(r)q.insertAdjacentHTML('beforeend',`<p class="${r.isCorrect?'correct':'wrong'}">${r.isCorrect?'✓ Correct':'✗ Incorrect'}</p>`)});}catch(e){mockSubmitted=false;if(button)button.disabled=false;alert(e.message)}}
async function renderPerformance(){if(!user)return;location.hash='performance';$('performance').classList.remove('hide');$('performanceBox').innerHTML='<p>Loading performance...</p>';let list=[];try{list=await api('/api/subjects')}catch{}let all=JSON.parse(localStorage.getItem(performanceKey())||'{}'),attempts=Object.values(all).reduce((sum,item)=>sum+(item.attempts||0),0),best=Object.values(all).reduce((score,item)=>Math.max(score,item.bestPercentage||0),0);$('performanceBox').innerHTML=`<div class="stats"><div class="stat">Subjects<b>${list.length}</b></div><div class="stat">Attempts<b>${attempts}</b></div><div class="stat">Best Score<b>${best}%</b></div><div class="stat">Access<b>${user.purchased||user.role==='admin'?'Full':'Free'}</b></div></div><div class="performance-grid">${list.map(s=>{let p=all[s.id]||{};return `<div class="performance-card"><div><span class="performance-icon">${esc(s.shortName)}</span><b>${esc(s.name)}</b></div><span>Attempts <strong>${p.attempts||0}</strong></span><span>Latest <strong>${p.lastPercentage===undefined?'--':p.lastPercentage+'%'}</strong></span><span>Best <strong>${p.bestPercentage===undefined?'--':p.bestPercentage+'%'}</strong></span></div>`}).join('')}</div>`}
function applyView(){let hash=location.hash||'#home',view=hash.slice(1)||'home';['performance','video-lecture','study-tips','pricing','study','admin','simulation','contact'].forEach(id=>$(id)?.classList.add('hide'));$('home').classList.toggle('hide',view!=='home');$('subjects').classList.toggle('hide',view!=='home'&&view!=='subjects');if(view==='home'){ $('simulation')?.classList.remove('hide');$('contact')?.classList.remove('hide') }if(view==='subjects')loadSubjects();if(view==='performance')renderPerformance();if(view==='video-lecture'){$('video-lecture')?.classList.remove('hide');}if(view==='study-tips'){$('study-tips')?.classList.remove('hide');}if(view==='pricing'){$('pricing')?.classList.remove('hide');}}
window.addEventListener('hashchange',applyView);
document.querySelector('#performanceLink').onclick=renderPerformance;
document.querySelector('#videoLectureLink').onclick=()=>{location.hash='video-lecture';};
document.querySelector('#pricingLink').onclick=()=>{location.hash='pricing';};
function openCatalogLecture(subjectId,lectureId){
  const subjectItem=lectureCatalog.find(item=>item.id===subjectId),lecture=subjectItem?.lectures.find(item=>item.id===lectureId);
  if(!subjectItem||!lecture)return;
  const free=lecture.free===true||subjectItem.lectures.indexOf(lecture)===0;
  if(!free){
    if(!user){auth('login');return;}
    if(!purchaseItem(`videoCourse:${subjectId}`,`${subjectItem.name} course`,subjectItem.price)){return;}
      let progress=JSON.parse(localStorage.getItem(`dgca_lecture_progress_${subjectId}_${user.id}`)||'{}');progress[lectureId]=true;localStorage.setItem(`dgca_lecture_progress_${subjectId}_${user.id}`,JSON.stringify(progress));
      showLectureSubject(subjectId);
  }
      if(free){let progress=JSON.parse(localStorage.getItem(`dgca_lecture_progress_${subjectId}_${user?.id||'guest'}`)||'{}');progress[lectureId]=true;localStorage.setItem(`dgca_lecture_progress_${subjectId}_${user?.id||'guest'}`,JSON.stringify(progress));updateLectureProgress(subjectId,subjectItem.lectures);}
  $('videoTitle').textContent=lecture.title;
  $('videoFrame').src=toEmbedUrl(lecture.youtubeUrl);
  setPaidVideoProtection(!free);
  $('videoModal').classList.remove('hide');
}
function setPaidVideoProtection(enabled){
  paidVideoActive=enabled;
  $('videoModal').classList.toggle('paid-content-protected',enabled);
  $('pdfModal').classList.toggle('paid-content-protected',enabled);
  if(protectionTimer)clearInterval(protectionTimer);
  protectionTimer=enabled?setInterval(checkDevToolsResize,1500):null;
}
function hideProtectionWarning(){$('protectionWarning')?.classList.add('hide')}
function showProtectionWarning(message='Copying, printing, screenshots, and developer tools are restricted on this website.'){
  if($('protectionMessage'))$('protectionMessage').textContent=message;
  $('protectionWarning')?.classList.remove('hide');
}
function checkDevToolsResize(){
  if(window.outerWidth-window.innerWidth>160||window.outerHeight-window.innerHeight>160){
    document.body.classList.add('inspection-detected');
    showProtectionWarning('Developer tools may be open. Protected content is hidden.');
  }else document.body.classList.remove('inspection-detected');
}
function editableTarget(target){return target.closest?.('input,textarea,[contenteditable="true"]')}
['contextmenu','selectstart','copy','cut','paste','dragstart'].forEach(type=>document.addEventListener(type,event=>{
  if(editableTarget(event.target))return;
  event.preventDefault();
  if(['copy','cut','contextmenu','selectstart'].includes(type))showProtectionWarning('Copying, selection, and context-menu actions are restricted.');
},true));
document.addEventListener('keydown',event=>{
  let key=event.key.toLowerCase(),command=event.ctrlKey||event.metaKey;
  let blocked=key==='printscreen'||key==='f12'||key==='snapshot'||(command&&['s','p','u'].includes(key))||(command&&event.shiftKey&&['i','j','c'].includes(key));
  if(blocked){event.preventDefault();event.stopPropagation();showProtectionWarning(key==='printscreen'?'Screenshots are restricted on this website.':'This browser shortcut is restricted.');}
},true);
window.addEventListener('beforeprint',event=>{event.preventDefault();showProtectionWarning('Printing is restricted on this website.');});
window.addEventListener('blur',()=>document.body.classList.add('window-unfocused'));
window.addEventListener('focus',()=>document.body.classList.remove('window-unfocused'));
window.addEventListener('resize',checkDevToolsResize);
setInterval(checkDevToolsResize,1500);
document.addEventListener('visibilitychange',()=>document.body.classList.toggle('window-unfocused',document.visibilityState==='hidden'));
if(navigator.mediaDevices?.getDisplayMedia)navigator.mediaDevices.getDisplayMedia=()=>Promise.reject(new DOMException('Screen capture is disabled.','NotAllowedError'));
function toEmbedUrl(url){
  try{let parsed=new URL(url);if(parsed.hostname.includes('youtube.com')&&parsed.pathname==='/watch')return `https://www.youtube.com/embed/${parsed.searchParams.get('v')||''}`;if(parsed.hostname==='youtu.be')return `https://www.youtube.com/embed${parsed.pathname}`;return url}catch{return url}
}
function openVideoLecture(type,freeMode=false){
  const subjectItem=lectureCatalog.find(item=>item.id===type);
  if(subjectItem?.lectures[0])openCatalogLecture(type,subjectItem.lectures[0].id);
}
loadLectureCatalog();
applyView();
async function loadAdmin(){try{let s=await api('/api/admin/stats');$('adminBox').innerHTML=`<div class="stats"><div class="stat">Users<b>${s.users}</b></div><div class="stat">Paid Users<b>${s.paidUsers}</b></div><div class="stat">Questions<b>${s.questions}</b></div><div class="stat">Purchases<b>${s.purchases}</b></div></div>`}catch{}}
