require('dotenv').config();
const express=require('express'),path=require('path'),fs=require('fs'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),crypto=require('crypto'),Razorpay=require('razorpay'),{createClient}=require('@supabase/supabase-js');
const app=express(),PORT=process.env.PORT||5000,SECRET=process.env.JWT_SECRET||'dev-secret',DEMO=String(process.env.DEMO_MODE||'true').toLowerCase()==='true';
const DATA=path.join(__dirname,'data'),QB=path.join(__dirname,'question-bank');
const U=path.join(DATA,'users.json'),P=path.join(DATA,'purchases.json');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
const toCamel=(k)=>{const s=String(k||'');const map={passwordhash:'passwordHash',createdat:'createdAt',userid:'userId',orderid:'orderId',paymentid:'paymentId'};return map[s.toLowerCase()]||s.replace(/_([a-z])/g,(_,c)=>c.toUpperCase());};
const normalizeSupabaseRow=row=>{if(!row||typeof row!=='object')return row;const out={};Object.entries(row).forEach(([key,value])=>{out[toCamel(key)]=value;});return out};
const normalizeSupabaseRows=rows=>Array.isArray(rows)?rows.map(normalizeSupabaseRow):[];
const supabaseEnabled = String(process.env.USE_SUPABASE||'false').toLowerCase()==='true' && !!process.env.SUPABASE_URL && !!process.env.SUPABASE_SERVICE_ROLE_KEY;
const supabase = supabaseEnabled ? createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}) : null;

async function getUsers(){if(!supabase)return read(U);try{const{data,error}=await supabase.from('users').select('*');if(error)throw error;return Array.isArray(data)&&data.length ? normalizeSupabaseRows(data) : read(U);}catch{return read(U);}}
async function saveUsers(users){if(!supabase){write(U,users);return;}try{const{error}=await supabase.from('users').upsert(users.map(u=>({...u,createdAt:u.createdAt||new Date().toISOString()})),{onConflict:'id'});if(error)throw error;}catch{write(U,users);}}
async function getPurchases(){if(!supabase)return read(P);try{const{data,error}=await supabase.from('purchases').select('*');if(error)throw error;return Array.isArray(data)&&data.length ? normalizeSupabaseRows(data) : read(P);}catch{return read(P);}}
async function savePurchases(purchases){if(!supabase){write(P,purchases);return;}try{const{error}=await supabase.from('purchases').upsert(purchases.map(p=>({...p,createdAt:p.createdAt||new Date().toISOString()})),{onConflict:'id'});if(error)throw error;}catch{write(P,purchases);}}

async function admin(){let u=await getUsers(),email=(process.env.ADMIN_EMAIL||'admin@dgcaprep.local').toLowerCase();if(!u.find(x=>x.email===email)){u.push({id:crypto.randomUUID(),name:'Administrator',email,passwordHash:bcrypt.hashSync(process.env.ADMIN_PASSWORD||'Admin@12345',12),role:'admin',createdAt:new Date().toISOString()});await saveUsers(u);}}
admin().catch(()=>{});
const subjects=()=>read(path.join(QB,'subjects.json')); const normalizeChapter=(id,chapter)=>{if(id!=='technical-general')return chapter;let value=String(chapter||'General').trim().toLowerCase();if(value==='overview'||value==='chapter 1')return 'Overview';if(value==='atomsphere'||value==='atmosphere')return 'Atmosphere';if(value==='basic aerodynamic theory')return 'Basic Aerodynamic Theory';if(value==='subsonic flow')return 'Subsonic Flow';return String(chapter||'General').trim()}; const questionList=value=>Array.isArray(value)?value:Object.values(value||{}).flatMap(group=>Array.isArray(group)?group:[]); const qs=id=>{let s=subjects().find(x=>x.id===id);if(!s)return[];if(Array.isArray(s.books))return s.books.flatMap(book=>fs.existsSync(path.join(QB,book.file))?questionList(read(path.join(QB,book.file))).map(q=>({...q,chapter:normalizeChapter(id,q.chapter),bookId:book.id,book:book.name})):[]);return fs.existsSync(path.join(QB,s.file))?questionList(read(path.join(QB,s.file))).map(q=>({...q,chapter:normalizeChapter(id,q.chapter)})):[]};
const MOCK_LIMITS={'air-regulations':50,meteorology:50,'piper-archer-iii':50,rtr:50,'air-navigation':100,'technical-general':100};
const shuffle=items=>{let result=[...items];for(let index=result.length-1;index>0;index--){let swap=Math.floor(Math.random()*(index+1));[result[index],result[swap]]=[result[swap],result[index]];}return result};
const findEmail=async e=>(await getUsers()).find(x=>x.email===String(e||'').trim().toLowerCase()); const findId=async id=>(await getUsers()).find(x=>x.id===id);
const purchased=async id=>(await getPurchases()).some(x=>x.userId===id&&x.status==='paid');
const pub=async u=>({id:u.id,name:u.name,email:u.email,role:u.role,purchased:await purchased(u.id)});
function auth(req,res,next){let h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):'';if(!t)return res.status(401).json({message:'Login required'});try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({message:'Session expired'})}}
function adminOnly(req,res,next){if(req.user.role!=='admin')return res.status(403).json({message:'Admin access required'});next()}
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
app.get('/api/config',async(q,r)=>r.json({demoMode:DEMO,razorpayEnabled:!!(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET),amount:+(process.env.RAZORPAY_PLAN_AMOUNT||499),currency:process.env.CURRENCY||'INR',supabaseEnabled:!!supabase}));
app.get('/api/supabase/health',(q,r)=>r.json({enabled:!!supabase,url:supabaseEnabled?process.env.SUPABASE_URL:'not-configured'}));
app.post('/api/auth/register',async(req,res)=>{let{name,email,password}=req.body||{};email=String(email||'').trim().toLowerCase();if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});if(password.length<6)return res.status(400).json({message:'Password must be at least 6 characters'});if(await findEmail(email))return res.status(409).json({message:'Email already registered'});let u={id:crypto.randomUUID(),name:String(name).trim(),email,passwordHash:await bcrypt.hash(password,12),role:'user',createdAt:new Date().toISOString()};let all=await getUsers();all.push(u);await saveUsers(all);res.json({token:jwt.sign({id:u.id,email:u.email,role:u.role},SECRET,{expiresIn:'7d'}),user:await pub(u)})});
app.post('/api/auth/login',async(req,res)=>{let u=await findEmail(req.body.email);if(!u||!(await bcrypt.compare(req.body.password||'',u.passwordHash)))return res.status(401).json({message:'Invalid email or password'});res.json({token:jwt.sign({id:u.id,email:u.email,role:u.role},SECRET,{expiresIn:'7d'}),user:await pub(u)})});
app.get('/api/auth/me',auth,async(req,res)=>{let u=await findId(req.user.id);if(!u)return res.status(401).json({message:'User not found'});res.json({user:await pub(u)})});
app.get('/api/subjects',auth,async(req,res)=>{let paid=await purchased(req.user.id)||req.user.role==='admin';res.json(subjects().map(s=>({...s,unlocked:s.access==='free'||paid})))})
app.get('/api/subjects/:id',auth,async(req,res)=>{let s=subjects().find(x=>x.id===req.params.id);if(!s)return res.status(404).json({message:'Subject not found'});if(s.access==='paid'&&!await purchased(req.user.id)&&req.user.role!=='admin')return res.status(402).json({message:'Paid question bank. Please purchase access.'});let practice=req.query.mode==='practice',questions=qs(s.id),book=req.query.book,chapter=req.query.chapter;if(book)questions=questions.filter(q=>q.bookId===book);if(chapter)questions=questions.filter(q=>q.chapter===chapter);if(!practice){questions=shuffle(questions);if(MOCK_LIMITS[s.id])questions=questions.slice(0,MOCK_LIMITS[s.id]);}let books=Array.isArray(s.books)?s.books.map(item=>{let bookQuestions=qs(s.id).filter(q=>q.bookId===item.id),chapterNames=[...new Set(bookQuestions.map(q=>String(q.chapter||'General').trim()))];return {...item,chapters:chapterNames.length?chapterNames.map(name=>({name,count:bookQuestions.filter(q=>String(q.chapter||'General').trim()===name).length})):[]};}) : null;res.json({subject:s,totalQuestions:questions.length,books,chapters:[...new Set(questions.map(q=>q.chapter||'General'))],questions:questions.map((q,i)=>({id:q.id||String(i+1),question:q.question,options:q.options,chapter:q.chapter||'General',bookId:q.bookId,book:q.book,difficulty:q.difficulty||'medium',...(practice?{answer:+q.answer}: {})}))})});
app.post('/api/subjects/:id/check',auth,async(req,res)=>{let s=subjects().find(x=>x.id===req.params.id);if(!s)return res.status(404).json({message:'Subject not found'});if(s.access==='paid'&&!await purchased(req.user.id)&&req.user.role!=='admin')return res.status(402).json({message:'Paid access required'});let ans=req.body.answers||{},results=qs(s.id).filter(q=>Object.prototype.hasOwnProperty.call(ans,q.id)).map(q=>({id:q.id,selected:+ans[q.id],correct:+q.answer,isCorrect:+ans[q.id]===+q.answer,explanation:q.explanation||''})),score=results.filter(x=>x.isCorrect).length;res.json({score,attempted:results.length,percentage:results.length?Math.round(score/results.length*100):0,results})});
app.post('/api/payment/create-order',auth,async(req,res)=>{if(DEMO)return res.json({demo:true});let key=process.env.RAZORPAY_KEY_ID,secret=process.env.RAZORPAY_KEY_SECRET;if(!key||!secret)return res.status(503).json({message:'Razorpay not configured. Keep DEMO_MODE=true for testing.'});try{let z=new Razorpay({key_id:key,key_secret:secret}),o=await z.orders.create({amount:+(process.env.RAZORPAY_PLAN_AMOUNT||499)*100,currency:process.env.CURRENCY||'INR',receipt:'dgca_'+Date.now()});res.json({demo:false,keyId:key,orderId:o.id,amount:o.amount,currency:o.currency})}catch(e){res.status(500).json({message:'Could not create payment order'})}});
app.post('/api/payment/demo-success',auth,async(req,res)=>{if(!DEMO)return res.status(403).json({message:'Demo disabled'});let p=await getPurchases();p.push({id:crypto.randomUUID(),userId:req.user.id,status:'paid',provider:'demo',amount:+(process.env.RAZORPAY_PLAN_AMOUNT||499),createdAt:new Date().toISOString()});await savePurchases(p);res.json({success:true})});
app.post('/api/payment/verify',auth,async(req,res)=>{if(DEMO)return res.status(400).json({message:'Use demo payment'});let{razorpay_order_id:o,razorpay_payment_id:p,razorpay_signature:s}=req.body||{};if(!o||!p||!s)return res.status(400).json({message:'Incomplete payment data'});let expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(o+'|'+p).digest('hex');if(expected!==s)return res.status(400).json({message:'Payment verification failed'});let all=await getPurchases();all.push({id:crypto.randomUUID(),userId:req.user.id,status:'paid',provider:'razorpay',orderId:o,paymentId:p,amount:+(process.env.RAZORPAY_PLAN_AMOUNT||499),createdAt:new Date().toISOString()});await savePurchases(all);res.json({success:true})});
app.get('/api/admin/stats',auth,adminOnly,async(req,res)=>{let us=await getUsers(),ps=await getPurchases();res.json({users:us.length,paidUsers:new Set(ps.filter(x=>x.status==='paid').map(x=>x.userId)).size,purchases:ps.length,subjects:subjects().length,questions:subjects().reduce((n,s)=>n+qs(s.id).length,0)})});
app.get('/api/admin/users',auth,adminOnly,async(req,res)=>{let users=await getUsers();res.json(await Promise.all(users.map(async u=>({...await pub(u),createdAt:u.createdAt}))))});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`DGCAPrep: http://localhost:${PORT} | Demo payments: ${DEMO} | Supabase: ${supabaseEnabled}`));
